# Generated by Django 3.0.2 on 2020-05-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.IntegerField()),
            ],
        ),
    ]
