# Generated by Django 3.0.2 on 2020-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0002_system_inf'),
    ]

    operations = [
        migrations.AddField(
            model_name='shumeipai',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
