# Generated by Django 3.0.2 on 2020-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0004_shumeipai_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shumeipai',
            name='remarks',
            field=models.CharField(max_length=200),
        ),
    ]
