# Generated by Django 3.0.2 on 2020-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0005_auto_20200507_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shumeipai',
            name='remarks',
            field=models.CharField(default='暂无备注', max_length=200),
        ),
    ]
