# Generated by Django 3.0.2 on 2020-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0006_auto_20200508_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='无', max_length=200),
        ),
    ]
