# Generated by Django 3.0.2 on 2020-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0008_auto_20200508_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_data',
            name='ph',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='main_data',
            name='sun',
            field=models.FloatField(default=1000),
        ),
    ]
