# Generated by Django 3.0.2 on 2020-05-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0008_auto_20200508_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shumeipai_limited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_max', models.FloatField(default=60)),
                ('tem_min', models.FloatField(default=0)),
                ('hum_max', models.FloatField(default=80)),
                ('hum_min', models.FloatField(default=0)),
                ('shumeipai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shumeipai.Shumeipai')),
            ],
        ),
    ]
