# Generated by Django 3.0.2 on 2020-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shumeipai', '0010_shumeipai_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='shumeipai_limited',
            name='switch',
            field=models.BooleanField(default=True),
        ),
    ]
